name: "🐞 Bug Fix"
description: "버그 수정"
labels: [ "bug", "fix" ]
body:
  - type: textarea
    attributes:
      label: 📄 버그 설명
      description: "해결할 버그의 현상 및 발생 상황에 대해 설명해 주세요."
      placeholder: "예시: 로그인 시 500 에러 발생, 데이터가 정상적으로 저장되지 않음"
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🔄 수정 사항
      description: "이번 변경으로 수정된 사항이나 추가된 기능, 그리고 문제를 해결하기 위해 적용한 방법이나 접근 방식을 설명해 주세요."
      placeholder: "예시: 로그인 서비스에서 발생한 예외 처리 추가"
    validations:
      required: false
